INSERT INTO Athlete VALUES ("001149", "BORGERK", "Karla", "Beach Volleyball", "Germany");
INSERT INTO Athlete VALUES ("001150", "BORGESA", "Alexis", "Handball", "Portugal");
INSERT INTO Athlete VALUES ("001151", "BORGESALMEIDASILVAM", "Mauricio", "Volleyball", "Brazil");
INSERT INTO Athlete VALUES ("001152", "BORGESF", "Felipe", "Handball", "Brazil");
INSERT INTO Athlete VALUES ("001153", "BORGESG", "Gabriel", "Sailing", "Brazil");
INSERT INTO Athlete VALUES ("001154", "BORGLIS", "Stine", "Cycling Road", "Norway");
INSERT INTO Athlete VALUES ("001155", "BORGOHAINL", "Lovlina", "Boxing", "India");
INSERT INTO Athlete VALUES ("001156", "BORKOWSKIM", "Mateusz", "Athletics", "Poland");
INSERT INTO Athlete VALUES ("001157", "BORLEED", "Dylan", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001158", "BORLEEJ", "Jonathan", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001159", "BORLEEK", "Kevin", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001160", "BORODACHEVK", "Kirill", "Fencing", "ROC");
INSERT INTO Athlete VALUES ("001161", "BORODAVKOJ", "Jevgenijs", "Judo", "Latvia");
INSERT INTO Athlete VALUES ("001162", "BORODINI", "Ilia", "Swimming", "ROC");
INSERT INTO Athlete VALUES ("001163", "BOROWSKAD", "Dorota", "Canoe Sprint", "Poland");
INSERT INTO Athlete VALUES ("001164", "BORRASM", "Marion", "Cycling Track", "France");
INSERT INTO Athlete VALUES ("001165", "BORREROMOLINAI", "Ismael", "Wrestling", "Cuba");
INSERT INTO Athlete VALUES ("001166", "BORTHWICKE", "Emily", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001167", "BORUTTAS", "Samantha", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001168", "BORYKAUM", "Mikita", "Canoe Sprint", "Belarus");
INSERT INTO Athlete VALUES ("001169", "BOSETTICC", "Caterina Chiara", "Volleyball", "Italy");
INSERT INTO Athlete VALUES ("001170", "BOSHNAKA", "Aliya", "Athletics", "Jordan");
INSERT INTO Athlete VALUES ("001171", "BOSKOVICT", "Tijana", "Volleyball", "Serbia");
INSERT INTO Athlete VALUES ("001172", "BOSSEPA", "Pierre Ambroise", "Athletics", "France");
INSERT INTO Athlete VALUES ("001173", "BOSSERHOFFN", "Niklas", "Hockey", "Germany");
INSERT INTO Athlete VALUES ("001174", "BOSSUYTS", "Shari", "Cycling Track", "Belgium");
INSERT INTO Athlete VALUES ("001175", "BOSWORTHS", "Sam", "Rowing", "New Zealand");
INSERT INTO Athlete VALUES ("001176", "BOSWORTHT", "Tom", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001177", "BOTALOVAM", "Maria", "Rowing", "ROC");
INSERT INTO Athlete VALUES ("001178", "BOTEKA", "Adam", "Canoe Sprint", "Slovakia");
INSERT INTO Athlete VALUES ("001179", "BOTINCHEVERD", "Diego", "Sailing", "Spain");
INSERT INTO Athlete VALUES ("001180", "BOTITUV", "Vilimoni", "Rugby Sevens", "Fiji");
INSERT INTO Athlete VALUES ("001181", "BOTLOGETSWEC", "Christine", "Athletics", "Botswana");
INSERT INTO Athlete VALUES ("001182", "BOTTCJ", "", "Football", "New Zealand");
INSERT INTO Athlete VALUES ("001183", "BOTTAROV", "Viviana", "Karate", "Italy");
INSERT INTO Athlete VALUES ("001184", "BOTTICHERS", "Stefan", "Cycling Track", "Germany");
INSERT INTO Athlete VALUES ("001185", "BOUALAMR", "Roumaysa", "Boxing", "Algeria");
INSERT INTO Athlete VALUES ("001186", "BOUBAKRII", "Ines", "Fencing", "Tunisia");
INSERT INTO Athlete VALUES ("001187", "BOUCHERONH", "Hugo", "Rowing", "France");
INSERT INTO Athlete VALUES ("001188", "BOUCHICHAH", "Hichem", "Athletics", "Algeria");
INSERT INTO Athlete VALUES ("001189", "BOUDINASA", "Sid Ali", "Rowing", "Algeria");
INSERT INTO Athlete VALUES ("001190", "BOUDJEMLINEA", "Adem", "Wrestling", "Algeria");
INSERT INTO Athlete VALUES ("001191", "BOUGARDE", "Erica", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001192", "BOUGUERRAA", "Aymen", "Volleyball", "Tunisia");
INSERT INTO Athlete VALUES ("001193", "BOUKAAEG", "El Ghali", "Equestrian", "Morocco");
INSERT INTO Athlete VALUES ("001194", "BOUKHIAMR", "Ramzi", "Surfing", "Morocco");
INSERT INTO Athlete VALUES ("001195", "BOUKLIS", "Shirine", "Judo", "France");
INSERT INTO Athlete VALUES ("001196", "BOULOUDINATSC", "Chouaib", "Boxing", "Algeria");
INSERT INTO Athlete VALUES ("001197", "BOUMAA", "Andrea", "Athletics", "Netherlands");
INSERT INTO Athlete VALUES ("001198", "BOUQANTARS", "Soufiyan", "Athletics", "Morocco");
INSERT INTO Athlete VALUES ("001199", "BOURASH", "Hamza", "Sailing", "Algeria");
INSERT INTO Athlete VALUES ("001200", "BOUREZM", "Michel", "Surfing", "France");
INSERT INTO Athlete VALUES ("001201", "BOURHISJP", "Jean Pierre", "Canoe Slalom", "Senegal");
INSERT INTO Athlete VALUES ("001202", "BOURIAHL", "Larbi", "Table Tennis", "Algeria");
INSERT INTO Athlete VALUES ("001203", "BOURKEC", "Colin", "Rugby Sevens", "Japan");
INSERT INTO Athlete VALUES ("001204", "BOURMPOUCI", "Christina Ioanna", "Rowing", "Greece");
INSERT INTO Athlete VALUES ("001205", "BOURNET", "Tri", "Beach Volleyball", "United States of America");
INSERT INTO Athlete VALUES ("001206", "BOUSETAS", "Siwar", "Wrestling", "Tunisia");
INSERT INTO Athlete VALUES ("001207", "BOUTBIENJ", "Jeanne", "Swimming", "Senegal");
INSERT INTO Athlete VALUES ("001208", "BOUTERM", "Micaela", "Diving", "South Africa");
INSERT INTO Athlete VALUES ("001209", "BOUTIERC", "Celine", "Golf", "France");
INSERT INTO Athlete VALUES ("001210", "BOUTOUILS", "Samy", "Swimming", "Morocco");
INSERT INTO Athlete VALUES ("001211", "BOUWMEESTERM", "Marit", "Sailing", "Netherlands");
INSERT INTO Athlete VALUES ("001212", "BOUZAYANIM", "Marwa", "Athletics", "Tunisia");
INSERT INTO Athlete VALUES ("001213", "BOVEC", "Claire", "Rowing", "France");
INSERT INTO Athlete VALUES ("001214", "BOVENDEERTR", "Roel", "Hockey", "Netherlands");
INSERT INTO Athlete VALUES ("001215", "BOWENA", "Alex", "Water Polo", "United States of America");
INSERT INTO Athlete VALUES ("001216", "BOWENK", "Katie", "Football", "New Zealand");
INSERT INTO Athlete VALUES ("001217", "BOYCEB", "Brendan", "Athletics", "Ireland");
INSERT INTO Athlete VALUES ("001218", "BOYERM", "Marine", "Artistic Gymnastics", "France");
INSERT INTO Athlete VALUES ("001219", "BOYERS", "Stephen", "Volleyball", "France");
INSERT INTO Athlete VALUES ("001220", "BOZM", "Meryem", "Volleyball", "Turkey");
INSERT INTO Athlete VALUES ("001221", "BOZAND", "Dilara", "Karate", "Turkey");
INSERT INTO Athlete VALUES ("001222", "BOZBAYEVI", "Islam", "Judo", "Kazakhstan");
INSERT INTO Athlete VALUES ("001223", "BRADSHAWH", "Holly", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001224", "BRADYJ", "Jennifer", "Tennis", "United States of America");
INSERT INTO Athlete VALUES ("001225", "BRAEGGERP", "Pablo", "Artistic Gymnastics", "Switzerland");
INSERT INTO Athlete VALUES ("001226", "BRAENDLEN", "Naemi", "Canoe Slalom", "Switzerland");
INSERT INTO Athlete VALUES ("001227", "BRAGAGUIMARAESG", "Gabriela", "Volleyball", "Brazil");
INSERT INTO Athlete VALUES ("001228", "BRAGANCAR", "Rui", "Taekwondo", "Portugal");
INSERT INTO Athlete VALUES ("001229", "BRAGMAYERZ", "Zsanett", "Triathlon", "Hungary");
INSERT INTO Athlete VALUES ("001230", "BRAIDC", "Connor", "Rugby Sevens", "Canada");
INSERT INTO Athlete VALUES ("001231", "BRAIDOTL", "Luca", "Cycling Mountain Bike", "Italy");
INSERT INTO Athlete VALUES ("001232", "BRAITC", "Camila", "Volleyball", "Brazil");
INSERT INTO Athlete VALUES ("001233", "BRAKEM", "Michael", "Rowing", "New Zealand");
INSERT INTO Athlete VALUES ("001234", "BRANDT", "Tim", "Hockey", "Australia");
INSERT INTO Athlete VALUES ("001235", "BRANDAUE", "Elisabeth", "Cycling Mountain Bike", "Germany");
INSERT INTO Athlete VALUES ("001236", "BRANDLM", "Maximilian", "Cycling Mountain Bike", "Germany");
INSERT INTO Athlete VALUES ("001237", "BRANKOVSKIB", "Borjan", "Shooting", "North Macedonia");
INSERT INTO Athlete VALUES ("001238", "BRANQUINHOD", "Diogo", "Handball", "Portugal");
INSERT INTO Athlete VALUES ("001239", "BRANSERM", "Marie", "Judo", "Democratic Republic of the Congo");
INSERT INTO Athlete VALUES ("001240", "BRANZMS", "Maria Sol", "Sailing", "Argentina");
INSERT INTO Athlete VALUES ("001241", "BRASHS", "Scott", "Equestrian", "Great Britain");
INSERT INTO Athlete VALUES ("001242", "BRASPENNINCXS", "Shanne", "Cycling Track", "Netherlands");
INSERT INTO Athlete VALUES ("001243", "BRASSARTM", "Maellyse", "Artistic Gymnastics", "Belgium");
INSERT INTO Athlete VALUES ("001244", "BRATHWAITES", "Shane", "Athletics", "Barbados");
INSERT INTO Athlete VALUES ("001245", "BRATTSETDALEK", "Kari", "Handball", "Norway");
INSERT INTO Athlete VALUES ("001246", "BRAUNSCHWEIGO", "Ole", "Swimming", "Germany");
INSERT INTO Athlete VALUES ("001247", "BRAUSSEF", "Franziska", "Cycling Track", "Germany");
INSERT INTO Athlete VALUES ("001248", "BRAVOC", "Claudio", "Football", "Argentina");
INSERT INTO Athlete VALUES ("001249", "BRAVOE", "Elizabeth", "Triathlon", "Ecuador");
INSERT INTO Athlete VALUES ("001250", "BRAYLOUGHEEDA", "Alanna", "Canoe Sprint", "Canada");
INSERT INTO Athlete VALUES ("001251", "BRAZT", "Thiago", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001252", "BRAZIERK", "Kelly", "Rugby Sevens", "New Zealand");
INSERT INTO Athlete VALUES ("001253", "BRECCIAROLIS", "Stefano", "Equestrian", "Italy");
INSERT INTO Athlete VALUES ("001254", "BREDALOFTEDALS", "Stine", "Handball", "Norway");
INSERT INTO Athlete VALUES ("001255", "BREISTOELK", "Kristine", "Handball", "Norway");
INSERT INTO Athlete VALUES ("001256", "BREMBACHN", "Nils", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001257", "BRENDELS", "Sebastian", "Canoe Sprint", "Germany");
INSERT INTO Athlete VALUES ("001258", "BRENNANE", "Emmet", "Boxing", "Ireland");
INSERT INTO Athlete VALUES ("001259", "BRENNAUERL", "Lisa", "Cycling Road", "Germany");
INSERT INTO Athlete VALUES ("001260", "BRENNO", "", "Football", "Brazil");
INSERT INTO Athlete VALUES ("001261", "BRESK", "Klaudia", "Shooting", "Poland");
INSERT INTO Athlete VALUES ("001262", "BREWC", "Chloe", "Rowing", "Great Britain");
INSERT INTO Athlete VALUES ("001263", "BRGULJAND", "Drasko", "Water Polo", "Montenegro");
INSERT INTO Athlete VALUES ("001264", "BRIELST", "Thomas", "Hockey", "Belgium");
INSERT INTO Athlete VALUES ("001265", "BRIERJ", "Joseph", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001266", "BRIGDENJONESJ", "Jo", "Canoe Sprint", "Australia");
INSERT INTO Athlete VALUES ("001267", "BRIGHTM", "Millie", "Football", "Great Britain");
INSERT INTO Athlete VALUES ("001268", "BRINEGARM", "Michael", "Swimming", "United States of America");
INSERT INTO Athlete VALUES ("001269", "BRINKMANT", "Thierry", "Hockey", "Netherlands");
INSERT INTO Athlete VALUES ("001270", "BRITTAINL", "Lawrence", "Rowing", "South Africa");
INSERT INTO Athlete VALUES ("001271", "BRIZARDA", "Antoine", "Volleyball", "France");
INSERT INTO Athlete VALUES ("001272", "BRNOVICT", "Tatjana", "Handball", "Montenegro");
INSERT INTO Athlete VALUES ("001273", "BROS", "Signe", "Swimming", "Denmark");
INSERT INTO Athlete VALUES ("001274", "BROCKL", "Laura", "Football", "Australia");
INSERT INTO Athlete VALUES ("001275", "BRODERSENS", "Svend", "Football", "Germany");
INSERT INTO Athlete VALUES ("001276", "BRODKAA", "Amelia", "Skateboarding", "Poland");
INSERT INTO Athlete VALUES ("001277", "BROEDERSB", "Ben", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001278", "BROEKSMAG", "Gijs", "Archery", "Netherlands");
INSERT INTO Athlete VALUES ("001279", "BROEKXL", "Lize", "Canoe Sprint", "Belgium");
INSERT INTO Athlete VALUES ("001280", "BROENINKS", "Stef", "Rowing", "Netherlands");
INSERT INTO Athlete VALUES ("001281", "BROERSENN", "Nadine", "Athletics", "Netherlands");
INSERT INTO Athlete VALUES ("001282", "BROMELLT", "Trayvon", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001283", "BROMFIELDJ", "Junelle", "Athletics", "Jamaica");
INSERT INTO Athlete VALUES ("001284", "BROMLEYM", "Michelle", "Table Tennis", "Australia");
INSERT INTO Athlete VALUES ("001285", "BRONZEL", "Lucy", "Football", "Great Britain");
INSERT INTO Athlete VALUES ("001286", "BROOKSD", "Declan", "Cycling BMX Freestyle", "Great Britain");
INSERT INTO Athlete VALUES ("001287", "BROOKSJ", "Jelena", "Basketball", "Serbia");
INSERT INTO Athlete VALUES ("001288", "BROOKSHIRES", "Suzannah", "Baseball/Softball", "Mexico");
INSERT INTO Athlete VALUES ("001289", "BROSSIERA", "Amandine", "Athletics", "France");
INSERT INTO Athlete VALUES ("001290", "BROSZUSB", "Blake", "Fencing", "Canada");
INSERT INTO Athlete VALUES ("001291", "BROUGHTONG", "Gayle", "Rugby Sevens", "New Zealand");
INSERT INTO Athlete VALUES ("001292", "BROUWERA", "Alexander", "Beach Volleyball", "Netherlands");
INSERT INTO Athlete VALUES ("001293", "BROWNA", "Abbie", "Rugby Sevens", "Great Britain");
INSERT INTO Athlete VALUES ("001294", "BROWNA", "Alicia", "Athletics", "Canada");
INSERT INTO Athlete VALUES ("001295", "BROWNC", "Colton", "Judo", "United States of America");
INSERT INTO Athlete VALUES ("001296", "BROWNE", "Erika", "Swimming", "United States of America");
INSERT INTO Athlete VALUES ("001297", "BROWNG", "Grace", "Cycling Road", "Australia");
INSERT INTO Athlete VALUES ("001298", "BROWNI", "Ira", "3x3 Basketball", "Japan");
INSERT INTO Athlete VALUES ("001299", "BROWNJ", "Javeir", "Athletics", "Jamaica");
INSERT INTO Athlete VALUES ("001300", "BROWNJ", "Joanna", "Triathlon", "Canada");
INSERT INTO Athlete VALUES ("001301", "BROWNM", "Maceo", "Rugby Sevens", "United States of America");
INSERT INTO Athlete VALUES ("001302", "BROWNM", "Mackenzie", "Archery", "United States of America");
INSERT INTO Athlete VALUES ("001303", "BROWNM", "Max", "Canoe Sprint", "New Zealand");
INSERT INTO Athlete VALUES ("001304", "BROWNR", "Ricardo", "Boxing", "Jamaica");
INSERT INTO Athlete VALUES ("001305", "BROWNS", "Sky", "Skateboarding", "Great Britain");
INSERT INTO Athlete VALUES ("001306", "BROWNEK", "Kwesi", "Cycling Track", "Trinidad and Tobago");
INSERT INTO Athlete VALUES ("001307", "BROWNINGK", "Kayle", "Shooting", "United States of America");
INSERT INTO Athlete VALUES ("001308", "BROWNINGR", "Rohan", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001309", "BROWNLEEJ", "Jonathan", "Triathlon", "Great Britain");
INSERT INTO Athlete VALUES ("001310", "BRUCEL", "Lauren", "Athletics", "New Zealand");
INSERT INTO Athlete VALUES ("001311", "BRUCEN", "Nick", "Cycling BMX Freestyle", "United States of America");
INSERT INTO Athlete VALUES ("001312", "BRUECKLERJ", "Julia", "Skateboarding", "Austria");
INSERT INTO Athlete VALUES ("001313", "BRUESSLERS", "Sarah", "Canoe Sprint", "Germany");
INSERT INTO Athlete VALUES ("001314", "BRUGGEMANL", "Lore", "Skateboarding", "Belgium");
INSERT INTO Athlete VALUES ("001315", "BRUHNA", "Annika", "Swimming", "Germany");
INSERT INTO Athlete VALUES ("001316", "BRUMEE", "Ese", "Athletics", "Nigeria");
INSERT INTO Athlete VALUES ("001317", "BRUNK", "Kristoffer", "Rowing", "Norway");
INSERT INTO Athlete VALUES ("001318", "BRUNETM", "Manon", "Fencing", "France");
INSERT INTO Athlete VALUES ("001319", "BRUNIR", "Rachele", "Marathon Swimming", "Italy");
INSERT INTO Athlete VALUES ("001320", "BRUNIR", "Roberta", "Athletics", "Italy");
INSERT INTO Athlete VALUES ("001321", "BRUSSINON", "Nicolas", "Basketball", "Argentina");
INSERT INTO Athlete VALUES ("001322", "BRUYNSEELSN", "Niels", "Equestrian", "Belgium");
INSERT INTO Athlete VALUES ("001323", "BRYDOND", "David", "Hockey", "New Zealand");
INSERT INTO Athlete VALUES ("001324", "BRYLM", "Michal", "Beach Volleyball", "Poland");
INSERT INTO Athlete VALUES ("001325", "BRYST", "Tim", "Rowing", "Belgium");
INSERT INTO Athlete VALUES ("001326", "BRYZHINAA", "Anastasiya", "Athletics", "Ukraine");
INSERT INTO Athlete VALUES ("001327", "BRZEZINSKIM", "Marcin", "Rowing", "Poland");
INSERT INTO Athlete VALUES ("001328", "BRZOZOWSKIA", "Artur", "Athletics", "Poland");
INSERT INTO Athlete VALUES ("001329", "BUARISHY", "Yousif", "Swimming", "Saudi Arabia");
INSERT INTO Athlete VALUES ("001330", "BUT", "Tingkai", "Canoe Sprint", "People's Republic of China");
INSERT INTO Athlete VALUES ("001331", "BUBLIKA", "Alexander", "Tennis", "Kazakhstan");
INSERT INTO Athlete VALUES ("001332", "BUCHANANK", "Kadeisha", "Football", "Canada");
INSERT INTO Athlete VALUES ("001333", "BUCHANANR", "Rushlee", "Cycling Track", "New Zealand");
INSERT INTO Athlete VALUES ("001334", "BUCHARDA", "Amandine", "Judo", "France");
INSERT INTO Athlete VALUES ("001335", "BUCHERS", "Simon", "Swimming", "Austria");
INSERT INTO Athlete VALUES ("001336", "BUCHLIM", "Matthijs", "Cycling Track", "Netherlands");
INSERT INTO Athlete VALUES ("001337", "BUCHMANNE", "Emanuel", "Cycling Road", "Germany");
INSERT INTO Athlete VALUES ("001338", "BUCKC", "Charlotte", "Rowing", "United States of America");
INSERT INTO Athlete VALUES ("001339", "BUCKINGHAMB", "Ben", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001340", "BUCKINGHAMC", "Charlie", "Sailing", "United States of America");
INSERT INTO Athlete VALUES ("001341", "BUCKLEC", "Carolyn", "Artistic Swimming", "Australia");
INSERT INTO Athlete VALUES ("001342", "BUCKLINGH", "Hannah", "Water Polo", "Australia");
INSERT INTO Athlete VALUES ("001343", "BUCZEKJ", "Jakub", "Rowing", "Canada");
INSERT INTO Athlete VALUES ("001344", "BUDCHARERNSA", "Siri Arun", "Swimming", "Lao People's Democratic Republic");
INSERT INTO Athlete VALUES ("001345", "BUDIAKA", "Anatolii", "Cycling Road", "Ukraine");
INSERT INTO Athlete VALUES ("001346", "BUENOL", "Laura", "Athletics", "Spain");
INSERT INTO Athlete VALUES ("001347", "BUFONIL", "Leticia", "Skateboarding", "Brazil");
INSERT INTO Athlete VALUES ("001348", "BUGAJSKIJ", "Josh", "Rowing", "Great Britain");
INSERT INTO Athlete VALUES ("001349", "BUGALLOAF", "Agustin Fernando", "Hockey", "Argentina");
INSERT INTO Athlete VALUES ("001350", "BUHLHANSENL", "Laerke", "Sailing", "Denmark");
INSERT INTO Athlete VALUES ("001351", "BUHUSI", "Iuliana", "Rowing", "Romania");
INSERT INTO Athlete VALUES ("001352", "BUIK", "Kim", "Artistic Gymnastics", "Germany");
INSERT INTO Athlete VALUES ("001353", "BUISAP", "Pam", "Rugby Sevens", "Canada");
INSERT INTO Athlete VALUES ("001354", "BUITENDAGB", "Bianca", "Surfing", "South Africa");
INSERT INTO Athlete VALUES ("001355", "BUJAKE", "Eugenia", "Cycling Road", "Slovenia");
INSERT INTO Athlete VALUES ("001356", "BUJOLDM", "Mandy", "Boxing", "Canada");
INSERT INTO Athlete VALUES ("001357", "BUKHOVV", "Vladyslav", "Swimming", "Ukraine");
INSERT INTO Athlete VALUES ("001358", "BUKICL", "Luka", "Water Polo", "Croatia");
INSERT INTO Athlete VALUES ("001359", "BUKOWIECKIK", "Konrad", "Athletics", "Poland");
INSERT INTO Athlete VALUES ("001360", "BULAICHSIMIAND", "Daniela", "Volleyball", "Argentina");
INSERT INTO Athlete VALUES ("001361", "BULLA", "Alyssa", "Canoe Sprint", "Australia");
INSERT INTO Athlete VALUES ("001362", "BULLT", "Tyson", "Artistic Gymnastics", "Australia");
INSERT INTO Athlete VALUES ("001363", "BULMERJ", "Josephine", "Canoe Sprint", "Australia");
INSERT INTO Athlete VALUES ("001364", "BULTORD", "Daryl", "Volleyball", "France");
INSERT INTO Athlete VALUES ("001365", "BUNDSENJ", "Johanna", "Handball", "Sweden");
INSERT INTO Athlete VALUES ("001366", "BUNGEC", "Claudia", "Football", "New Zealand");
INSERT INTO Athlete VALUES ("001367", "BURCHAMS", "Scotty", "Baseball/Softball", "Israel");
INSERT INTO Athlete VALUES ("001368", "BURCHELLR", "Remona", "Athletics", "Jamaica");
INSERT INTO Athlete VALUES ("001369", "BURDISSOF", "Federico", "Swimming", "Italy");
INSERT INTO Athlete VALUES ("001370", "BURESTEDTF", "Felix", "Badminton", "Sweden");
INSERT INTO Athlete VALUES ("001371", "BURGERA", "Alex", "Sailing", "South Africa");
INSERT INTO Athlete VALUES ("001372", "BURGERG", "Guillaume", "Canoe Sprint", "France");
INSERT INTO Athlete VALUES ("001373", "BURGESSA", "Adam", "Canoe Slalom", "Great Britain");
INSERT INTO Athlete VALUES ("001374", "BURGHARDTA", "Alexandra", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001375", "BURGOS", "Samuele", "Canoe Sprint", "Italy");
INSERT INTO Athlete VALUES ("001376", "BURIANK", "Katalin", "Swimming", "Hungary");
INSERT INTO Athlete VALUES ("001377", "BURKARDE", "Elena", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001378", "BURKEM", "Mario", "Athletics", "Barbados");
INSERT INTO Athlete VALUES ("001379", "BURKHILLH", "Hannah", "Artistic Swimming", "Australia");
INSERT INTO Athlete VALUES ("001380", "BURKSQ", "Quanesha", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001381", "BURLINGP", "Peter", "Sailing", "New Zealand");
INSERT INTO Athlete VALUES ("001382", "BURMANNOLIVEIRAPL", "Pedro Luis", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001383", "BURNETA", "Anna", "Sailing", "Great Britain");
INSERT INTO Athlete VALUES ("001384", "BURNETT", "Taymir", "Athletics", "Netherlands");
INSERT INTO Athlete VALUES ("001385", "BURNETTD", "Derek", "Shooting", "Ireland");
INSERT INTO Athlete VALUES ("001386", "BURNST", "Tom", "Taekwondo", "New Zealand");
INSERT INTO Athlete VALUES ("001387", "BURRELLK", "Keeno", "Athletics", "Jamaica");
INSERT INTO Athlete VALUES ("001388", "BURTONA", "Abi", "Rugby Sevens", "Great Britain");
INSERT INTO Athlete VALUES ("001389", "BUSAB", "Bianka", "Volleyball", "Serbia");
INSERT INTO Athlete VALUES ("001390", "BUSAL", "Luigi", "Karate", "Italy");
INSERT INTO Athlete VALUES ("001391", "BUSATOM", "Mattia", "Karate", "Italy");
INSERT INTO Athlete VALUES ("001392", "BUSCHK", "Kim", "Swimming", "Netherlands");
INSERT INTO Athlete VALUES ("001393", "BUSCOMBC", "Camille", "Athletics", "New Zealand");
INSERT INTO Athlete VALUES ("001394", "BUSLJEA", "Andro", "Water Polo", "Croatia");
INSERT INTO Athlete VALUES ("001395", "BUSSIERET", "Theo", "Swimming", "France");
INSERT INTO Athlete VALUES ("001396", "BUSTAMANTEC", "Carlos", "Baseball/Softball", "Mexico");
INSERT INTO Athlete VALUES ("001397", "BUSTOSE", "Esteban", "Modern Pentathlon", "Chile");
INSERT INTO Athlete VALUES ("001398", "BUSTOSSANCHEZA", "Alejandro", "Water Polo", "Spain");
INSERT INTO Athlete VALUES ("001399", "BUTBULT", "Tohar", "Judo", "Israel");
INSERT INTO Athlete VALUES ("001400", "BUTCHARTA", "Andrew", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001401", "BUTDEECD", "Chatchai Decha", "Boxing", "Thailand");
INSERT INTO Athlete VALUES ("001402", "BUTSENKOM", "Mykola", "Boxing", "Ukraine");
INSERT INTO Athlete VALUES ("001403", "BUTTERWORTHA", "Alycia", "Athletics", "Canada");
INSERT INTO Athlete VALUES ("001404", "BUTTERWORTHL", "Lindsey", "Athletics", "Canada");
INSERT INTO Athlete VALUES ("001405", "BUTTSTOWNSENDT", "Tynita", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001406", "BUTULIJAD", "Dajana", "Basketball", "Serbia");
INSERT INTO Athlete VALUES ("001407", "BUZARNESCUM", "Mihaela", "Tennis", "Romania");
INSERT INTO Athlete VALUES ("001408", "BWOGIS", "Shadiri", "Boxing", "Uganda");
INSERT INTO Athlete VALUES ("001409", "BYLONA", "Atheyna", "Boxing", "Panama");
INSERT INTO Athlete VALUES ("001410", "BYRNER", "Ronan", "Rowing", "Ireland");
INSERT INTO Athlete VALUES ("001411", "CAL", "Liliana", "Athletics", "Portugal");
INSERT INTO Athlete VALUES ("001412", "CABALJS", "Juan Sebastian", "Tennis", "Colombia");
INSERT INTO Athlete VALUES ("001413", "CABALLEROD", "Denia", "Athletics", "Cuba");
INSERT INTO Athlete VALUES ("001414", "CABANAPEREZC", "Cristina", "Judo", "Spain");
INSERT INTO Athlete VALUES ("001415", "CABECINHAA", "Ana", "Athletics", "Portugal");
INSERT INTO Athlete VALUES ("001416", "CABELICKAJ", "Jitka", "Cycling Mountain Bike", "Czech Republic");
INSERT INTO Athlete VALUES ("001417", "CABRALBARBOSAA", "Alexandrina", "Handball", "Spain");
INSERT INTO Athlete VALUES ("001418", "CABRERAM", "Melky", "Baseball/Softball", "Dominican Republic");
INSERT INTO Athlete VALUES ("001419", "CACACEL", "Liberato", "Football", "New Zealand");
INSERT INTO Athlete VALUES ("001420", "CACCIAMANII", "Ilaria", "Baseball/Softball", "Italy");
INSERT INTO Athlete VALUES ("001421", "CACERESE", "Eusebio", "Athletics", "Spain");
INSERT INTO Athlete VALUES ("001422", "CACIA", "Anthony", "Football", "France");
INSERT INTO Athlete VALUES ("001423", "CACICN", "Nikolina", "Boxing", "Croatia");
INSERT INTO Athlete VALUES ("001424", "CADOS", "Sasa", "Basketball", "Serbia");
INSERT INTO Athlete VALUES ("001425", "CADOGANS", "Shane", "Swimming", "St Vincent and the Grenadines");
INSERT INTO Athlete VALUES ("001426", "CAFFAROF", "Francisco", "Basketball", "Argentina");
INSERT INTO Athlete VALUES ("001427", "CAIA", "Alex", "Fencing", "Canada");
INSERT INTO Athlete VALUES ("001428", "CAIZ", "Zelin", "Athletics", "People's Republic of China");
INSERT INTO Athlete VALUES ("001429", "CAICEDOJ", "Juan", "Athletics", "Ecuador");
INSERT INTO Athlete VALUES ("001430", "CAICEDOPACHITOJC", "Jean Carlos", "Boxing", "Ecuador");
INSERT INTO Athlete VALUES ("001431", "CAINEROC", "Chiara", "Shooting", "Italy");
INSERT INTO Athlete VALUES ("001432", "CAIRAJ", "Jenna", "Baseball/Softball", "Canada");
INSERT INTO Athlete VALUES ("001433", "CAIRNSA", "Anne", "Canoe Sprint", "Samoa");
INSERT INTO Athlete VALUES ("001434", "CAIXETAT", "Tandara", "Volleyball", "Brazil");
INSERT INTO Athlete VALUES ("001435", "CAKIROGLUBN", "Buse Naz", "Boxing", "Turkey");
INSERT INTO Athlete VALUES ("001436", "CAKSSG", "Gatis", "Athletics", "Latvia");
INSERT INTO Athlete VALUES ("001437", "CALABROG", "Giulio", "Sailing", "Italy");
INSERT INTO Athlete VALUES ("001438", "CALDERANOH", "Hugo", "Table Tennis", "Brazil");
INSERT INTO Athlete VALUES ("001439", "CALDWELLA", "Abbey", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001440", "CALELJO", "Jose Oswaldo", "Athletics", "Guatemala");
INSERT INTO Athlete VALUES ("001441", "CALISKANK", "Kubra", "Volleyball", "Turkey");
INSERT INTO Athlete VALUES ("001442", "CALJAB", "Briken", "Weightlifting", "Albania");
INSERT INTO Athlete VALUES ("001443", "CALJOUWM", "Mark", "Badminton", "Netherlands");
INSERT INTO Athlete VALUES ("001444", "CALLEGARIB", "Beatrice", "Artistic Swimming", "Italy");
INSERT INTO Athlete VALUES ("001445", "CAMACHOQUINNJ", "Jasmine", "Athletics", "Puerto Rico");
INSERT INTO Athlete VALUES ("001446", "CAMARAE", "Ebrima", "Athletics", "Gambia");
INSERT INTO Athlete VALUES ("001447", "CAMARAFY", "Fatoumata Yarie", "Wrestling", "Guinea");
INSERT INTO Athlete VALUES ("001448", "CAMARAS", "Seco", "Athletics", "Guinea-Bissau");
INSERT INTO Athlete VALUES ("001449", "CAMBONIM", "Mattia", "Sailing", "Italy");
INSERT INTO Athlete VALUES ("001450", "CAMERONL", "Lloydricia", "Athletics", "Jamaica");
INSERT INTO Athlete VALUES ("001451", "CAMILOOLIVEIRAPA", "Paulo Andre", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001452", "CAMPAZZOF", "Facundo", "Basketball", "Argentina");
INSERT INTO Athlete VALUES ("001453", "CAMPBELLB", "Bronte", "Swimming", "Australia");
INSERT INTO Athlete VALUES ("001454", "CAMPBELLC", "Cate", "Swimming", "Australia");
INSERT INTO Athlete VALUES ("001455", "CAMPBELLEJ", "Emily Jade", "Weightlifting", "Great Britain");
INSERT INTO Athlete VALUES ("001456", "CAMPBELLJ", "Jane", "Football", "United States of America");
INSERT INTO Athlete VALUES ("001457", "CAMPBELLJ", "Jesse", "Equestrian", "New Zealand");
INSERT INTO Athlete VALUES ("001458", "CAMPBELLL", "Luke", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001459", "CAMPBELLP", "Paige", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001460", "CAMPBELLR", "Richard", "Water Polo", "Australia");
INSERT INTO Athlete VALUES ("001461", "CAMPBELLT", "Taylor", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001462", "CAMPBELLT", "Teniel", "Cycling Road", "Trinidad and Tobago");
INSERT INTO Athlete VALUES ("001463", "CAMPIONK", "Kevin", "Athletics", "France");
INSERT INTO Athlete VALUES ("001464", "CAMPOSJ", "Jorge", "Table Tennis", "Cuba");
INSERT INTO Athlete VALUES ("001465", "CAMPOSL", "Luiza", "Rugby Sevens", "Brazil");
INSERT INTO Athlete VALUES ("001466", "CAMPOSLH", "Luis Henry", "Athletics", "Peru");
INSERT INTO Athlete VALUES ("001467", "CAMPOSN", "Natalia", "Football", "Chile");
INSERT INTO Athlete VALUES ("001468", "CAMPOSPEREIRARH", "Rafael Henrique", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001469", "CAMPOSR", "Rafael", "Golf", "Puerto Rico");
INSERT INTO Athlete VALUES ("001470", "CAMPOST", "Tiago", "Marathon Swimming", "Portugal");
INSERT INTO Athlete VALUES ("001471", "CAMPUZANOCHAVEZPEOND", "Daniela", "Cycling Mountain Bike", "Mexico");
INSERT INTO Athlete VALUES ("001472", "CANY", "Yasemin", "Athletics", "Turkey");
INSERT INTO Athlete VALUES ("001473", "CANALEJOPAZOSJ", "Jaime", "Rowing", "Spain");
INSERT INTO Athlete VALUES ("001474", "CANALESA", "Antonia", "Football", "Chile");
INSERT INTO Athlete VALUES ("001475", "CANCARV", "Vlatko", "Basketball", "Slovenia");
INSERT INTO Athlete VALUES ("001476", "CANELOSANCHEZEA", "Eliecer Alfonso", "Volleyball", "Venezuela");
INSERT INTO Athlete VALUES ("001477", "CANETTK", "Kayla", "Rugby Sevens", "United States of America");
INSERT INTO Athlete VALUES ("001478", "CANNONER", "Romain", "Fencing", "France");
INSERT INTO Athlete VALUES ("001479", "CANORUIZC", "Carmen", "Hockey", "Spain");
INSERT INTO Athlete VALUES ("001480", "CANTERR", "Rosalind", "Equestrian", "Great Britain");
INSERT INTO Athlete VALUES ("001481", "CANTEROREINAP", "Patricia", "Sailing", "Spain");
INSERT INTO Athlete VALUES ("001482", "CANUELKA", "Karol Ann", "Cycling Road", "Canada");
INSERT INTO Athlete VALUES ("001483", "CAPDEVILLEG", "Gustavo", "Handball", "Portugal");
INSERT INTO Athlete VALUES ("001484", "CAPOBIANCOA", "Andrew", "Diving", "United States of America");
INSERT INTO Athlete VALUES ("001485", "CAPOGROSSON", "Nicolas", "Beach Volleyball", "Argentina");
INSERT INTO Athlete VALUES ("001486", "CAPORASOT", "Teodorico", "Athletics", "Italy");
INSERT INTO Athlete VALUES ("001487", "CARAMBULARAURICHAI", "Adrian Ignacio", "Beach Volleyball", "Italy");
INSERT INTO Athlete VALUES ("001488", "CARAMIGNOLIMR", "Martina Rita", "Swimming", "Italy");
INSERT INTO Athlete VALUES ("001489", "CARAPAZR", "Richard", "Cycling Road", "Ecuador");
INSERT INTO Athlete VALUES ("001490", "CARBALLESBAENAR", "Roberto", "Tennis", "Spain");
INSERT INTO Athlete VALUES ("001491", "CARBONELLBALLESTEROO", "Ona", "Artistic Swimming", "Spain");
INSERT INTO Athlete VALUES ("001492", "CARDD", "Devon", "Water Polo", "South Africa");
INSERT INTO Athlete VALUES ("001493", "CARDK", "Kelsey", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001494", "CARDAA", "Ally", "Baseball/Softball", "United States of America");
INSERT INTO Athlete VALUES ("001495", "CARDENASESTRADAJA", "Jorge Adan", "Weightlifting", "Mexico");
INSERT INTO Athlete VALUES ("001496", "CARDONAMENDEZJ", "Joan", "Sailing", "Spain");
INSERT INTO Athlete VALUES ("001497", "CARDOSOA", "Adriana", "Handball", "Brazil");
INSERT INTO Athlete VALUES ("001498", "CARDOZOROJASIV", "Irismar Valle", "Boxing", "Venezuela");
INSERT INTO Athlete VALUES ("001499", "CAREYJ", "Jade", "Artistic Gymnastics", "United States of America");
INSERT INTO Athlete VALUES ("001500", "CAREYM", "Michelle", "Hockey", "Ireland");
INSERT INTO Athlete VALUES ("001501", "CARGNIND", "Daniel", "Judo", "Brazil");
INSERT INTO Athlete VALUES ("001502", "CARINIG", "Giacomo", "Swimming", "Italy");
INSERT INTO Athlete VALUES ("001503", "CARIOLOUA", "Andreas", "Sailing", "Cyprus");
INSERT INTO Athlete VALUES ("001504", "CARLEG", "Gabrielle", "Football", "Canada");
INSERT INTO Athlete VALUES ("001505", "CARLETONB", "Bridget", "Basketball", "Canada");
INSERT INTO Athlete VALUES ("001506", "CARLIS", "Sarah", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001507", "CARLILET", "Thomas", "Equestrian", "France");
INSERT INTO Athlete VALUES ("001508", "CARLINJ", "Jack", "Cycling Track", "Great Britain");
INSERT INTO Athlete VALUES ("001509", "CARLOSA", "Azenaide", "Handball", "Angola");
INSERT INTO Athlete VALUES ("001510", "CARLSBOGARDJ", "Jonathan", "Handball", "Sweden");
INSERT INTO Athlete VALUES ("001511", "CARLSONJ", "Jenny", "Handball", "Sweden");
INSERT INTO Athlete VALUES ("001512", "CARNEGIES", "Sholto", "Rowing", "Great Britain");
INSERT INTO Athlete VALUES ("001513", "CARONARVAEZA", "Angelo", "Skateboarding", "Peru");
INSERT INTO Athlete VALUES ("001514", "CAROSONEE", "Emily", "Baseball/Softball", "Italy");
INSERT INTO Athlete VALUES ("001515", "CAROUGM", "Gonzalo Matias", "Handball", "Argentina");
INSERT INTO Athlete VALUES ("001516", "CARPENTERE", "Ellie", "Football", "Australia");
INSERT INTO Athlete VALUES ("001517", "CARPREAUXM", "Marjorie", "Basketball", "Belgium");
INSERT INTO Athlete VALUES ("001518", "CARRANZASAROLIC", "Cecilia", "Sailing", "Argentina");
INSERT INTO Athlete VALUES ("001519", "CARRAROM", "Martina", "Swimming", "Italy");
INSERT INTO Athlete VALUES ("001520", "CARRASCOANGULOJM", "Jose Manuel", "Volleyball", "Venezuela");
INSERT INTO Athlete VALUES ("001521", "CARRERAQUINTANAR", "Raquel", "Basketball", "Spain");
INSERT INTO Athlete VALUES ("001522", "CARRIERM", "Marina", "Modern Pentathlon", "Australia");
INSERT INTO Athlete VALUES ("001523", "CARRILLOD", "Duilio", "Modern Pentathlon", "Mexico");
INSERT INTO Athlete VALUES ("001524", "CARRILLOM", "Marko", "Shooting", "Peru");
INSERT INTO Athlete VALUES ("001525", "CARRILLOY", "Yeseida", "Athletics", "Colombia");
INSERT INTO Athlete VALUES ("001526", "CARRINGTONL", "Lisa", "Canoe Sprint", "New Zealand");
INSERT INTO Athlete VALUES ("001527", "CARROF", "Fernando", "Athletics", "Spain");
INSERT INTO Athlete VALUES ("001528", "CARROLLN", "Naomi", "Hockey", "Ireland");
INSERT INTO Athlete VALUES ("001529", "CARSTENSENSF", "Sebastian Fini", "Cycling Mountain Bike", "Denmark");
INSERT INTO Athlete VALUES ("001530", "CARTERA", "Anthony", "Baseball/Softball", "United States of America");
INSERT INTO Athlete VALUES ("001531", "CARTERC", "Chris", "Athletics", "United States of America");
INSERT INTO Athlete VALUES ("001532", "CARTERD", "Dylan", "Swimming", "Trinidad and Tobago");
INSERT INTO Athlete VALUES ("001533", "CARUSOB", "Bianca", "Sailing", "Italy");
INSERT INTO Athlete VALUES ("001534", "CARUSOD", "Damiano", "Cycling Road", "Italy");
INSERT INTO Athlete VALUES ("001535", "CARVALHOL", "Lucas", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001536", "CASASQ", "Queralt", "Basketball", "Spain");
INSERT INTO Athlete VALUES ("001537", "CASAST", "Triston", "Baseball/Softball", "United States of America");
INSERT INTO Athlete VALUES ("001538", "CASELLASCHUTHM", "Maico", "Hockey", "Argentina");
INSERT INTO Athlete VALUES ("001539", "CASETTAB", "Belen", "Athletics", "Argentina");
INSERT INTO Athlete VALUES ("001540", "CASEYP", "Paul", "Golf", "Great Britain");
INSERT INTO Athlete VALUES ("001541", "CASHINA", "Amy", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001542", "CASILLASGARCIAM", "Miriam", "Triathlon", "Spain");
INSERT INTO Athlete VALUES ("001543", "CASLICKC", "Charlotte", "Rugby Sevens", "Australia");
INSERT INTO Athlete VALUES ("001544", "CASSANDROT", "Tammaro", "Shooting", "Italy");
INSERT INTO Athlete VALUES ("001545", "CASSARAA", "Andrea", "Fencing", "Italy");
INSERT INTO Athlete VALUES ("001546", "CASSEM", "Matthias", "Judo", "Belgium");
INSERT INTO Athlete VALUES ("001547", "CASSIEMAD", "Abdud Dayaan", "Hockey", "South Africa");
INSERT INTO Athlete VALUES ("001548", "CASSIEMM", "Mustaphaa", "Hockey", "South Africa");
INSERT INTO Athlete VALUES ("001549", "CASSINA", "Alexandre", "Table Tennis", "France");
INSERT INTO Athlete VALUES ("001550", "CASSONJ", "Jennifer", "Rowing", "Canada");
INSERT INTO Athlete VALUES ("001551", "CASTALDOM", "Matteo", "Rowing", "Italy");
INSERT INTO Athlete VALUES ("001552", "CASTANEDAJA", "Jhon Alexander", "Athletics", "Colombia");
INSERT INTO Athlete VALUES ("001553", "CASTANOGARCIAG", "Gabriel", "Swimming", "Mexico");
INSERT INTO Athlete VALUES ("001554", "CASTELBLANCOJ", "Jorge", "Athletics", "Panama");
INSERT INTO Athlete VALUES ("001555", "CASTELLANOSSOANEZM", "Mercedes", "Handball", "Spain");
INSERT INTO Athlete VALUES ("001556", "CASTILLOB", "Brenda", "Volleyball", "Dominican Republic");
INSERT INTO Athlete VALUES ("001557", "CASTILLOGALINDOR", "Rut", "Rhythmic Gymnastics", "Mexico");
INSERT INTO Athlete VALUES ("001558", "CASTILLOG", "Gabriel", "Swimming", "Bolivia");
INSERT INTO Athlete VALUES ("001559", "CASTILLOL", "Luis", "Baseball/Softball", "Dominican Republic");
INSERT INTO Athlete VALUES ("001560", "CASTILLOTORRESJC", "Julio Cesar", "Boxing", "Ecuador");
INSERT INTO Athlete VALUES ("002265", "DELGADILLOD", "Daniel", "Marathon Swimming", "Mexico");
INSERT INTO Athlete VALUES ("002266", "DELGADOA", "Angelica", "Judo", "United States of America");
INSERT INTO Athlete VALUES ("002267", "DELGADOA", "Anicka", "Swimming", "Ecuador");
INSERT INTO Athlete VALUES ("002268", "DELIAM", "Marcos", "Basketball", "Argentina");
INSERT INTO Athlete VALUES ("002269", "DELILAJM", "Manuela", "Shooting", "Albania");
INSERT INTO Athlete VALUES ("002270", "DELLAQUILAV", "Vito", "Taekwondo", "Italy");
INSERT INTO Athlete VALUES ("002271", "DELLAVEDOVAM", "Matthew", "Basketball", "Australia");
INSERT INTO Athlete VALUES ("002272", "DELLIENH", "Hugo", "Tennis", "Bolivia");
INSERT INTO Athlete VALUES ("002273", "DELMOTTEN", "Nicolas", "Equestrian", "France");
INSERT INTO Athlete VALUES ("002274", "DELRUED", "Delphine", "Badminton", "France");
INSERT INTO Athlete VALUES ("002275", "DEMAYC", "Coralie", "Cycling Track", "France");
INSERT INTO Athlete VALUES ("002276", "DEMEYV", "Valerie", "Cycling Road", "Belgium");
INSERT INTO Athlete VALUES ("002277", "DEMIDIKK", "Karyna", "Athletics", "Belarus");
INSERT INTO Athlete VALUES ("002278", "DEMIRE", "Evin", "Athletics", "Turkey");
INSERT INTO Athlete VALUES ("002279", "DEMIREVAM", "Mirela", "Athletics", "Bulgaria");
