INSERT INTO Country VALUES ("United States of America", "1", "113");
INSERT INTO Country VALUES ("People's Republic of China", "2", "88");
INSERT INTO Country VALUES ("Japan", "3", "58");
INSERT INTO Country VALUES ("Great Britain", "4", "65");
INSERT INTO Country VALUES ("ROC", "5", "71");
INSERT INTO Country VALUES ("Australia", "6", "46");
INSERT INTO Country VALUES ("Netherlands", "7", "36");
INSERT INTO Country VALUES ("France", "8", "33");
INSERT INTO Country VALUES ("Germany", "9", "37");
INSERT INTO Country VALUES ("Italy", "10", "40");
INSERT INTO Country VALUES ("Canada", "11", "24");
INSERT INTO Country VALUES ("Brazil", "12", "21");
INSERT INTO Country VALUES ("New Zealand", "13", "20");
INSERT INTO Country VALUES ("Cuba", "14", "15");
INSERT INTO Country VALUES ("Hungary", "15", "20");
INSERT INTO Country VALUES ("Republic of Korea", "16", "20");
INSERT INTO Country VALUES ("Poland", "17", "14");
INSERT INTO Country VALUES ("Czech Republic", "18", "11");
INSERT INTO Country VALUES ("Kenya", "19", "10");
INSERT INTO Country VALUES ("Norway", "20", "8");
INSERT INTO Country VALUES ("Jamaica", "21", "9");
INSERT INTO Country VALUES ("Spain", "22", "17");
INSERT INTO Country VALUES ("Sweden", "23", "9");
INSERT INTO Country VALUES ("Switzerland", "24", "13");
INSERT INTO Country VALUES ("Denmark", "25", "11");
INSERT INTO Country VALUES ("Croatia", "26", "8");
INSERT INTO Country VALUES ("Islamic Republic of Iran", "27", "7");
INSERT INTO Country VALUES ("Serbia", "28", "9");
INSERT INTO Country VALUES ("Belgium", "29", "7");
INSERT INTO Country VALUES ("Bulgaria", "30", "6");
INSERT INTO Country VALUES ("Slovenia", "31", "5");
INSERT INTO Country VALUES ("Uzbekistan", "32", "5");
INSERT INTO Country VALUES ("Georgia", "33", "8");
INSERT INTO Country VALUES ("Chinese Taipei", "34", "12");
INSERT INTO Country VALUES ("Turkey", "35", "13");
INSERT INTO Country VALUES ("Greece", "36", "4");
INSERT INTO Country VALUES ("Uganda", "36", "4");
INSERT INTO Country VALUES ("Ecuador", "38", "3");
INSERT INTO Country VALUES ("Ireland", "39", "4");
INSERT INTO Country VALUES ("Israel", "39", "4");
INSERT INTO Country VALUES ("Qatar", "41", "3");
INSERT INTO Country VALUES ("Bahamas", "42", "2");
INSERT INTO Country VALUES ("Kosovo", "42", "2");
INSERT INTO Country VALUES ("Ukraine", "44", "19");
INSERT INTO Country VALUES ("Belarus", "45", "7");
INSERT INTO Country VALUES ("Romania", "46", "4");
INSERT INTO Country VALUES ("Venezuela", "46", "4");
INSERT INTO Country VALUES ("India", "48", "7");
INSERT INTO Country VALUES ("Hong Kong, China", "49", "6");
INSERT INTO Country VALUES ("Philippines", "50", "4");
INSERT INTO Country VALUES ("Slovakia", "50", "4");
INSERT INTO Country VALUES ("South Africa", "52", "3");
INSERT INTO Country VALUES ("Austria", "53", "7");
INSERT INTO Country VALUES ("Egypt", "54", "6");
INSERT INTO Country VALUES ("Indonesia", "55", "5");
INSERT INTO Country VALUES ("Ethiopia", "56", "4");
INSERT INTO Country VALUES ("Portugal", "56", "4");
INSERT INTO Country VALUES ("Tunisia", "58", "2");
INSERT INTO Country VALUES ("Estonia", "59", "2");
INSERT INTO Country VALUES ("Fiji", "59", "2");
INSERT INTO Country VALUES ("Latvia", "59", "2");
INSERT INTO Country VALUES ("Thailand", "59", "2");
INSERT INTO Country VALUES ("Bermuda", "63", "1");
INSERT INTO Country VALUES ("Morocco", "63", "1");
INSERT INTO Country VALUES ("Puerto Rico", "63", "1");
INSERT INTO Country VALUES ("Colombia", "66", "5");
INSERT INTO Country VALUES ("Azerbaijan", "67", "7");
INSERT INTO Country VALUES ("Dominican Republic", "68", "5");
INSERT INTO Country VALUES ("Armenia", "69", "4");
INSERT INTO Country VALUES ("Kyrgyzstan", "70", "3");
INSERT INTO Country VALUES ("Mongolia", "71", "4");
INSERT INTO Country VALUES ("Argentina", "72", "3");
INSERT INTO Country VALUES ("San Marino", "72", "3");
INSERT INTO Country VALUES ("Jordan", "74", "2");
INSERT INTO Country VALUES ("Malaysia", "74", "2");
INSERT INTO Country VALUES ("Nigeria", "74", "2");
INSERT INTO Country VALUES ("Bahrain", "77", "1");
INSERT INTO Country VALUES ("Saudi Arabia", "77", "1");
INSERT INTO Country VALUES ("Lithuania", "77", "1");
INSERT INTO Country VALUES ("North Macedonia", "77", "1");
INSERT INTO Country VALUES ("Namibia", "77", "1");
INSERT INTO Country VALUES ("Turkmenistan", "77", "1");
INSERT INTO Country VALUES ("Kazakhstan", "83", "8");
INSERT INTO Country VALUES ("Mexico", "84", "4");
INSERT INTO Country VALUES ("Finland", "85", "2");
INSERT INTO Country VALUES ("Botswana", "86", "1");
INSERT INTO Country VALUES ("Burkina Faso", "86", "1");
INSERT INTO Country VALUES ("Cote d'Ivoire", "86", "1");
INSERT INTO Country VALUES ("Ghana", "86", "1");
INSERT INTO Country VALUES ("Grenada", "86", "1");
INSERT INTO Country VALUES ("Kuwait", "86", "1");
INSERT INTO Country VALUES ("Republic of Moldova", "86", "1");
INSERT INTO Country VALUES ("Syrian Arab Republic", "86", "1");
