INSERT INTO Athlete VALUES ("001149", "BORGERK", "Karla", "Beach Volleyball", "Germany");
INSERT INTO Athlete VALUES ("001150", "BORGESA", "Alexis", "Handball", "Portugal");
INSERT INTO Athlete VALUES ("001151", "BORGESALMEIDASILVAM", "Mauricio", "Volleyball", "Brazil");
INSERT INTO Athlete VALUES ("001152", "BORGESF", "Felipe", "Handball", "Brazil");
INSERT INTO Athlete VALUES ("001153", "BORGESG", "Gabriel", "Sailing", "Brazil");
INSERT INTO Athlete VALUES ("001154", "BORGLIS", "Stine", "Cycling Road", "Norway");
INSERT INTO Athlete VALUES ("001155", "BORGOHAINL", "Lovlina", "Boxing", "India");
INSERT INTO Athlete VALUES ("001156", "BORKOWSKIM", "Mateusz", "Athletics", "Poland");
INSERT INTO Athlete VALUES ("001157", "BORLEED", "Dylan", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001158", "BORLEEJ", "Jonathan", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001159", "BORLEEK", "Kevin", "Athletics", "Belgium");
INSERT INTO Athlete VALUES ("001160", "BORODACHEVK", "Kirill", "Fencing", "ROC");
INSERT INTO Athlete VALUES ("001161", "BORODAVKOJ", "Jevgenijs", "Judo", "Latvia");
INSERT INTO Athlete VALUES ("001162", "BORODINI", "Ilia", "Swimming", "ROC");
INSERT INTO Athlete VALUES ("001163", "BOROWSKAD", "Dorota", "Canoe Sprint", "Poland");
INSERT INTO Athlete VALUES ("001164", "BORRASM", "Marion", "Cycling Track", "France");
INSERT INTO Athlete VALUES ("001165", "BORREROMOLINAI", "Ismael", "Wrestling", "Cuba");
INSERT INTO Athlete VALUES ("001166", "BORTHWICKE", "Emily", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001167", "BORUTTAS", "Samantha", "Athletics", "Germany");
INSERT INTO Athlete VALUES ("001168", "BORYKAUM", "Mikita", "Canoe Sprint", "Belarus");
INSERT INTO Athlete VALUES ("001169", "BOSETTICC", "Caterina Chiara", "Volleyball", "Italy");
INSERT INTO Athlete VALUES ("001170", "BOSHNAKA", "Aliya", "Athletics", "Jordan");
INSERT INTO Athlete VALUES ("001171", "BOSKOVICT", "Tijana", "Volleyball", "Serbia");
INSERT INTO Athlete VALUES ("001172", "BOSSEPA", "Pierre Ambroise", "Athletics", "France");
INSERT INTO Athlete VALUES ("001173", "BOSSERHOFFN", "Niklas", "Hockey", "Germany");
INSERT INTO Athlete VALUES ("001174", "BOSSUYTS", "Shari", "Cycling Track", "Belgium");
INSERT INTO Athlete VALUES ("001175", "BOSWORTHS", "Sam", "Rowing", "New Zealand");
INSERT INTO Athlete VALUES ("001176", "BOSWORTHT", "Tom", "Athletics", "Great Britain");
INSERT INTO Athlete VALUES ("001177", "BOTALOVAM", "Maria", "Rowing", "ROC");
INSERT INTO Athlete VALUES ("001178", "BOTEKA", "Adam", "Canoe Sprint", "Slovakia");
INSERT INTO Athlete VALUES ("001179", "BOTINCHEVERD", "Diego", "Sailing", "Spain");
INSERT INTO Athlete VALUES ("001180", "BOTITUV", "Vilimoni", "Rugby Sevens", "Fiji");
INSERT INTO Athlete VALUES ("001181", "BOTLOGETSWEC", "Christine", "Athletics", "Botswana");
INSERT INTO Athlete VALUES ("001182", "BOTTCJ", "", "Football", "New Zealand");
INSERT INTO Athlete VALUES ("001534", "CARUSOD", "Damiano", "Cycling Road", "Italy");
INSERT INTO Athlete VALUES ("001535", "CARVALHOL", "Lucas", "Athletics", "Brazil");
INSERT INTO Athlete VALUES ("001536", "CASASQ", "Queralt", "Basketball", "Spain");
INSERT INTO Athlete VALUES ("001537", "CASAST", "Triston", "Baseball/Softball", "United States of America");
INSERT INTO Athlete VALUES ("001538", "CASELLASCHUTHM", "Maico", "Hockey", "Argentina");
INSERT INTO Athlete VALUES ("001539", "CASETTAB", "Belen", "Athletics", "Argentina");
INSERT INTO Athlete VALUES ("001540", "CASEYP", "Paul", "Golf", "Great Britain");
INSERT INTO Athlete VALUES ("001541", "CASHINA", "Amy", "Athletics", "Australia");
INSERT INTO Athlete VALUES ("001542", "CASILLASGARCIAM", "Miriam", "Triathlon", "Spain");
INSERT INTO Athlete VALUES ("001543", "CASLICKC", "Charlotte", "Rugby Sevens", "Australia");
INSERT INTO Athlete VALUES ("001544", "CASSANDROT", "Tammaro", "Shooting", "Italy");
INSERT INTO Athlete VALUES ("001545", "CASSARAA", "Andrea", "Fencing", "Italy");
INSERT INTO Athlete VALUES ("001546", "CASSEM", "Matthias", "Judo", "Belgium");
INSERT INTO Athlete VALUES ("001547", "CASSIEMAD", "Abdud Dayaan", "Hockey", "South Africa");
INSERT INTO Athlete VALUES ("001548", "CASSIEMM", "Mustaphaa", "Hockey", "South Africa");
INSERT INTO Athlete VALUES ("001549", "CASSINA", "Alexandre", "Table Tennis", "France");
INSERT INTO Athlete VALUES ("001550", "CASSONJ", "Jennifer", "Rowing", "Canada");
INSERT INTO Athlete VALUES ("001551", "CASTALDOM", "Matteo", "Rowing", "Italy");